apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-dataverse.fullname" . }}
  labels:
    {{- include "demo-dataverse.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "demo-dataverse.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "demo-dataverse.labels" . | nindent 8 }}
        app.kubernetes.io/component: primary
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "demo-dataverse.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.extraEnvVars .Values.awsS3.enabled }}
          env:
            {{- if .Values.extraEnvVars }}
            {{- toYaml .Values.extraEnvVars | nindent 12 }}
            {{- end }}
            {{- if .Values.awsS3.enabled }}
            - name: aws_endpoint_url
              value: {{ .Values.awsS3.endpointUrl | quote }}
            - name: aws_bucket_name
              value: {{ .Values.awsS3.bucketName | quote }}
            - name: aws_s3_profile
              value: {{ .Values.awsS3.profile | quote }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or .Values.persistence.enabled .Values.configMap.enabled .Values.awsS3.enabled .Values.volumeMounts }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
            {{- end }}
            {{- if .Values.configMap.enabled }}
            - name: init-d
              mountPath: {{ .Values.configMap.mountPath }}
              readOnly: true
            {{- end }}
            {{- if .Values.awsS3.enabled }}
            - name: aws-cli
              mountPath: /secrets/aws-cli/.aws
              readOnly: true
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
      {{- if or .Values.persistence.enabled .Values.configMap.enabled .Values.awsS3.enabled .Values.volumes }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{ else }}{{ include "demo-dataverse.fullname" . }}-data{{ end }}
        {{- end }}
        {{- if .Values.configMap.enabled }}
        - name: init-d
          configMap:
            name: {{ include "demo-dataverse.fullname" . }}-config
            defaultMode: 0755
        {{- end }}
        {{- if .Values.awsS3.enabled }}
        - name: aws-cli
          secret:
            secretName: {{ required "awsS3.existingSecret is required when awsS3.enabled=true" .Values.awsS3.existingSecret | quote }}
            items:
              - key: {{ .Values.awsS3.secretKeys.credentials | quote }}
                path: credentials
              - key: {{ .Values.awsS3.secretKeys.config | quote }}
                path: config
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
